### ISSUE TITLE
Position constrain

### ISSUE THREAD

**Issue by juandopazo** [tilomitra/tipsy#3]
It'd be very useful to be able to constrain the position of the tipsy/popover so that it's always visible in the window.

**Comment by juandopazo** [comment]
I'll try to add this directly to widget-position-align.

**Comment by F21** [comment]
@juandopazo Has this been added to `widget-position-align`?

**Comment by juandopazo** [comment]
There is `widget-position-constrain`. See http://yuilibrary.com/yui/docs/api/modules/widget-position-constrain.html.
